version: '3'

services:
    client:
        build: ./app
        ports:
            - 3000:3000
        depends_on: 
            - api
        environment: 
            APIURL: https://api:8000
    
    api:
        build: ./api
        environment: 
            DBURI: DBURI
