DROP TABLE IF EXISTS species_water_joiner;
DROP TABLE IF EXISTS fishable_waters;
DROP TABLE IF EXISTS species;

DROP SCHEMA IF EXISTS etl CASCADE;
DROP EXTENSION IF EXISTS postgis CASCADE;
DROP EXTENSION IF EXISTS "uuid-ossp" CASCADE;